### ISSUE TITLE
Body Hash Did Not Verify

### ISSUE THREAD

**Issue by ninanoe** [Pro/dkim-exchange#300] opened 2020-04-19 02:53 UTC
### Versions

- **Windows Server Version**: 2016
- **Exchange Version**: 2016 CU16
- **Installed DKIM Exchange Version**: 3.2.4

### Description

mxtoolbox.com email header analyzer:  DKIM Signature ->  always reports, the body hash is different.  

When you send an email in plain text from exchange there is no issue .  DKIM Signature is verified.  
The problem is only there when you send email in html or rich text.  

I also tried this with office 365  with DKIM enabled and then is allways working.  

### Steps to Reproduce

1. Send email to gmail.com
2. copy the email headers to mxtoolbox email header analyzer
3. DKIM Signature body hash did not verify

**Expected behavior:**

Body hash to verify

**Actual behavior:**

Body Hash Did Not Verify
--

**Comment by dbeato** [comment] 2020-04-22 11:36
Having the same issue here.

**Comment by ninanoe** [comment] 2020-04-22 12:07
I'm kinda lost at understanding whats happening here.   

- Send normal email from outlook -> yahoo mail   -> Analyse the email headers ->  NO ISSUES ,  DKIM Alignment  + DKIM Authenticated

- Send normal email from outlook -> Google mail -> Analyse email ->  ISSUE , DKIM Authenticated is red -> Body hash dit not verify.       

I'm not sure where the problem lies.   Is it dkim-exchange tool ,  is it mxtoolbox.com who is wrong,  Or maybe its just Google gmail doing something to the email.

**Comment by dbeato** [comment] 2020-04-22 12:10
I actually did a check on my configuration. I moved up the DKIM transport agent to the top list (Lowest number). Restart the Exchange Transport Service and right now it is working. I was having the issue with the DKIM Transport agent at #3.

**Comment by DJBenson** [comment] 2020-04-24 11:51
Sounds very much like a duplicate of #252 which turned out to be a bug in MXToolbox' code. Every other DKIM verification tool I've used seems to validate my DKIM correctly but MXToolbox is failing on body signing (I hadn't even noticed until I checked this post but I'm sure it was working at home point).

List of sites I've used (mix of header and DKIM/DNS checkers):
https://dkimcore.org/tools/keycheck.html
https://dkimvalidator.com/
https://protodave.com/tools/dkim-key-checker/
https://www.appmaildev.com/en/dkim
https://www.dmarcanalyzer.com/dkim/dkim-check/
https://www.mail-tester.com/spf-dkim-check

Google also validates the DKIM.

A huge number of posts about this issue all point back towards MXToolbox, now that could be because it's one of the largest/most reputable sites out there, but it could also be because they are wrong with this issue - I'm not sure.

I'm really not sure this is a problem with the tool and it doesn't seem to be causing an issue with email delivery.

**Comment by DJBenson** [comment] 2020-04-24 12:24
> I actually did a check on my configuration. I moved up the DKIM transport agent to the top list (Lowest number). Restart the Exchange Transport Service and right now it is working. I was having the issue with the DKIM Transport agent at #3.

I tried that. For some reason my DKIM was configured as priority 1 (probably from some testing) but moved it down to priority 10 and it made no difference to the outcome on MXToolbox.

**Comment by DJBenson** [comment] 2020-06-07 14:53
Probable 3rd party issue.

**Closed by DJBenson** 2020-06-07 14:53 UTC
