### ISSUE TITLE
DKIM Exchange constantly crashes the MSExchangeTransport service (2010 SP3 CU14)

### ISSUE THREAD

**Issue by rhymeswithmogul** [Pro/dkim-exchange#162] opened 2016-10-11 03:17 UTC
### Versions
- **Windows Server Version**: Windows Server 2012, fully patched
- **Exchange Version**: Exchange Server 2010 SP3 CU14 (14.3.319.2)
- **Installed DKIM Exchange Version**: 3.0.6
### Description

When the transport rule is enabled, the Microsoft Exchange Transport service continually crashes and restarts.  Mail is not delivered to or from the server, and SMTP is unavailable.

The following logs are available in the Application log (source MSExchange Common, ID 4999):

> Watson report about to be sent for process id: [PID], with parameters: E12, c-RTL-AMD64, 14.03.0319.002, edgetransport, mscorlib, S.ThrowHelper.ThrowArgumentException, S.Reflection.TargetInvocationException, 6d6d, 02.00.50727.6421.
> ErrorReportingEnabled: True

This is the generated Report.wer file:

```
Version=1
EventType=E12
EventTime=131206286422308132
Consent=2
UploadTime=131206286422621997
ReportIdentifier=5bb26350-8f5f-11e6-946a-00155dab0200
Response.BucketId=952c0faa2ff4a2447e516e1da6baf92f
Response.BucketTable=5
Response.LegacyBucketId=127448841397
Response.type=4
Sig[0].Name=flavor
Sig[0].Value=c-RTL-AMD64
Sig[1].Name=appVersion
Sig[1].Value=14.03.0319.002
Sig[2].Name=appName
Sig[2].Value=edgetransport
Sig[3].Name=assemblyName
Sig[3].Value=mscorlib
Sig[4].Name=exMethodName
Sig[4].Value=S.ThrowHelper.ThrowArgumentException
Sig[5].Name=exceptionType
Sig[5].Value=S.Reflection.TargetInvocationException
Sig[6].Name=callstackHash
Sig[6].Value=6d6d
Sig[7].Name=assemblyVer
Sig[7].Value=02.00.50727.6421
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.2.9200.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=E12
ConsentKey=E12
AppName=EdgeTransport
AppPath=C:\Program Files\Microsoft\Exchange Server\V14\Bin\edgetransport.exe
```
### Steps to Reproduce
1. Install and configure DKIM Exchange.

**Expected behavior:** The transport service should stay running.

**Actual behavior:** The transport service crashes.

**Comment by Pro** [comment] 2016-12-13 11:39
Duplicate of #166

**Closed by Pro** 2016-12-13 11:39 UTC
