### ISSUE TITLE
Updgrade should use newly downloaded Configuration.exe

### ISSUE THREAD

**Issue by rbfajardo** [Pro/dkim-exchange#102] opened 2015-10-27 20:15 UTC
I am getting an error when upgrading DKIM from 2.1.6 to 2.1.7.

Your Microsoft Exchange version isn't supported by the DKIM agent: 15.0.1130.7
I upgraded Exchange 2013 to CU10

Attached screenshot of error and version in hex

![version_not_supported](https://cloud.githubusercontent.com/assets/187106/10771198/86738ba4-7cbd-11e5-8db7-a2ee08b5e486.PNG)
![exchange_version_hex](https://cloud.githubusercontent.com/assets/187106/10771199/87ed0762-7cbd-11e5-9e20-555e85bcafea.PNG)

**Comment by Pro** [comment] 2015-10-27 21:15
That's strange. It should be supported, at least the version is mentioned in the constants:
https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/Constants.cs#L38

Are you sure that you upgraded to 2.1.7? Because the second screenshot mentiones `2.1.5`. You can check the Properties Dialog of the .exe file (using Windows Explorer)

**Comment by gogglespisano** [comment] 2015-10-27 21:55
I don't know if it's related, but when I do the update or reiinstall option, it updates all the files except Configuration.DkimSigner.exe which has an in use error, so the UI says 2.1.5 but almost all the files are actually 2.1.7.

**Comment by rbfajardo** [comment] 2015-10-27 22:01
My mistake, I did not launch the 2.1.7 "Configuration.DkimSigner" executable. I thought I could launch the existing one and do an online update. After launching the correct version of the executable, the installer updated the files.

**Comment by Pro** [comment] 2015-10-27 22:04
This may be the root cause for this problem... When the Update process is launched, the old dkim signer should close, but it seems that it is hanging somewhare and thus not closing which causes the copy operation to fail.

Maybe this bug was introduced in 2.1.5 where we updated the install process (https://github.com/Pro/dkim-exchange/releases/tag/v2.1.5).
The upgrading still needs some improvement (e.g. check if Configuration.DkimSigner is still running)

@rbfajardo Online Update should theoretically work, but due to the bug described, it still launches the old version.

**Comment by AlexLaroche** [comment] 2015-10-27 22:15
The main problem is that we should load Constants.cs from a XML file that we can get versions of supported Exchange. During the upgrade process, we just have to load the new version of the xml file.

The problem is here in the code. (Install function)

```
foreach (KeyValuePair<string, string> entry in Constants.DKIM_SIGNER_VERSION_DIRECTORY)
{
     if (exchangeVersion.StartsWith(entry.Key))
     {
     agentExchangeVersionPath = entry.Value;
     break;
     }
}
```

**Comment by Pro** [comment] 2015-10-28 07:55
The Constants.cs file is probably not the problem why the Configuration.exe doesn't close?
Creating an XML file just moves the constants into another place, so this wouldn't change much. It even makes the code more complex.

Maybe it's better to create an installer instead of the current approach? I.E. using Inno Setup.
Then the Configuration.exe downloads the installer and executes it. This will result in a more robust way for copying and installing the files. And it may be easier for users to install the signer.

**Comment by AlexLaroche** [comment] 2015-10-28 12:18
The Constants.cs is part of the executable. You can't close the file without reaload the executable.

The variable DKIM_SIGNER_VERSION_DIRECTORY should be in a XML file that we can load and unload having to restart the configuration application.

If you want to try to create a installer you cant try but your installer will have to be able to call external program to call powershell.

```
    public static class Constants
    {
        public const string DKIM_SIGNER_PATH = @"C:\Program Files\Exchange DkimSigner";
        public const string DKIM_SIGNER_AGENT_NAME = @"Exchange DkimSigner";
        public const string DKIM_SIGNER_AGENT_DLL = @"ExchangeDkimSigner.dll";
        public const string DKIM_SIGNER_CONFIGURATION_EXE = @"Configuration.DkimSigner.exe";

        public const string DKIM_SIGNER_NOTICE = "This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
        public const string DKIM_SIGNER_LICENCE = "This Software is provided under the GNU GPLv3 License.\r\nFuther details can be found here: http://www.gnu.org/licenses";
        public const string DKIM_SIGNER_AUTHOR = "The code for the signing algorithm is based on the work of Nicholas Piasecki.\r\n\r\nDeveloped and maintained by Stefan Profanter and Alexandre Laroche.";
        public const string DKIM_SIGNER_WEBSITE = "Website : https://github.com/Pro/dkim-exchange";

        public const string DKIM_SIGNER_EVENTLOG_SOURCE = @"Exchange DKIM";
        public const string DKIM_SIGNER_EVENTLOG_REGISTRY = @"SYSTEM\CurrentControlSet\Services\EventLog\Application\Exchange DKIM";

        public static readonly Dictionary<string, string> DKIM_SIGNER_VERSION_DIRECTORY = new Dictionary<string, string>()
        {
            {"8.3.", "Exchange 2007 SP3"},
            {"14.0.", "Exchange 2010"},
            {"14.1.", "Exchange 2010 SP1"},
            {"14.2.", "Exchange 2010 SP2"},
            {"14.3.", "Exchange 2010 SP3"},
            {"15.0.516.32", "Exchange 2013"},
            {"15.0.620.29", "Exchange 2013 CU1"},
            {"15.0.712.24", "Exchange 2013 CU2"},
            {"15.0.775.38", "Exchange 2013 CU3"},
            {"15.0.847.32", "Exchange 2013 SP1 CU4"},
            {"15.0.913.22", "Exchange 2013 SP1 CU5"},
            {"15.0.995.29", "Exchange 2013 SP1 CU6"},
            {"15.0.1044.25", "Exchange 2013 SP1 CU7"},
            {"15.0.1076.9", "Exchange 2013 SP1 CU8"},
            {"15.0.1104.5", "Exchange 2013 SP1 CU9"},
            {"15.0.1130.7", "Exchange 2013 SP1 CU10"},
            {"15.1.225.17", "Exchange 2016 Preview"},
            {"15.1.225.42", "Exchange 2016 RTM"}
        };
    }
```

```
private void Install()
{
    this.btClose.Enabled = false;
    this.gbSelectVersionToInstall.Enabled = false;
    this.gbInstallStatus.Enabled = true;
    this.Refresh();

    // ###########################################
    // ### IS Exchange version supported?      ###
    // ###########################################

    string agentExchangeVersionPath = "";

    foreach (KeyValuePair<string, string> entry in Constants.DKIM_SIGNER_VERSION_DIRECTORY)
    {
        if (exchangeVersion.StartsWith(entry.Key))
        {
            agentExchangeVersionPath = entry.Value;
            break;
        }
    }

    if (agentExchangeVersionPath == "")
    {
        MessageBox.Show(this, "Your Microsoft Exchange version isn't supported by the DKIM agent: " + exchangeVersion, "Version not supported", MessageBoxButtons.OK, MessageBoxIcon.Error);
    }
    else
    {
        this.lbDownloadFiles.Enabled = true;
    }

    // ###########################################
    // ### Download files                      ###
    // ###########################################

    string zipFile = "";

    if (Uri.IsWellFormedUriString(this.zipUrl, UriKind.RelativeOrAbsolute))
    {
        zipFile = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + ".zip");

        DownloadProgressWindow oDpw = new DownloadProgressWindow(this.zipUrl, zipFile);
        try {
            if (oDpw.ShowDialog(this) == DialogResult.OK)
            {
                this.lbExtractFiles.Enabled = true;
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, "Couldn't initialize download progress window:\n" + ex.Message, "Error showing download progress", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
        finally
        {
            oDpw.Dispose();
        }
        
    }
    else
    {
        if (File.Exists(this.zipUrl) && Path.GetExtension(this.zipUrl) == ".zip")
        {
            zipFile = this.zipUrl;
            this.lbExtractFiles.Enabled = true;
        }
        else
        {
            MessageBox.Show(this, "The URL or the path to the ZIP file is invalid. Please try again.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    this.picDownloadFiles.Image = this.lbExtractFiles.Enabled ? this.statusImageList.Images[0] : this.statusImageList.Images[1];
    this.Refresh();

    // ###########################################
    // ### Extract files                       ###
    // ###########################################

    string extractPath = Path.Combine(Path.GetDirectoryName(zipFile), Path.GetFileNameWithoutExtension(zipFile));

    if (this.lbExtractFiles.Enabled)
    {
        if (!Directory.Exists(extractPath))
        {
            Directory.CreateDirectory(extractPath);
        }

        try
        {
            ZipFile.ExtractToDirectory(zipFile, extractPath);

            // copy root directory is one directory below extracted zip:
            string[] contents = Directory.GetDirectories(extractPath);
            if (contents.Length == 1)
            {
                extractPath = Path.Combine(extractPath, contents[0]);
                this.lbStopService.Enabled = true;
            }
            else
            {
                MessageBox.Show(this, "Downloaded .zip is invalid. Please try again.", "Invalid download", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }                   
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "ZIP Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    this.picExtractFiles.Image = this.lbStopService.Enabled ? this.statusImageList.Images[0] : this.statusImageList.Images[1];
    this.Refresh();

    // ###########################################
    // ### Stop Microsoft Transport service    ###
    // ###########################################

    if (this.lbStopService.Enabled)
    {
        if (this.transportService.GetStatus() != "Stopped")
        {
            this.transportServiceSuccessStatus = "Stopped";
            this.transportService.Do(TransportServiceAction.Stop);
            this.lbCopyFiles.Enabled = this.transportServiceActionCompleted.WaitOne();
        }
        else
        {
            this.lbCopyFiles.Enabled = true;
        }
    }

    this.picStopService.Image = this.lbCopyFiles.Enabled ? this.statusImageList.Images[0] : this.statusImageList.Images[1];
    this.Refresh();

    // ###########################################
    // ### Copy required files                 ###
    // ###########################################

    if (this.lbCopyFiles.Enabled)
    {
        List<string> filesToCopy = new List<string>();
        filesToCopy.Add(Path.Combine(extractPath, @"Src\Configuration.DkimSigner\bin\Release"));
        filesToCopy.Add(Path.Combine(extractPath, Path.Combine(@"Src\Exchange.DkimSigner\bin\" + agentExchangeVersionPath)));

        // IF the directory "C:\Program Files\Exchange DkimSigner" doesn't exist, create it 
        if (!Directory.Exists(Constants.DKIM_SIGNER_PATH))
        {
            Directory.CreateDirectory(Constants.DKIM_SIGNER_PATH);
        }

        // Generate list of source files
        string[] sourceFiles = new string[0];
        foreach (string sourcePath in filesToCopy)
        {
            string[] asTemp = Directory.GetFiles(sourcePath);

            Array.Resize(ref sourceFiles, sourceFiles.Length + asTemp.Length);
            Array.Copy(asTemp, 0, sourceFiles, sourceFiles.Length - asTemp.Length, asTemp.Length);
        }

        // Generate list of destinations files
        string[] destinationFiles = new string[sourceFiles.Length];
        for (int i = 0; i < sourceFiles.Length; i++)
        {
            string sFile = Path.GetFileName(sourceFiles[i]);
            destinationFiles[i] = Path.Combine(Constants.DKIM_SIGNER_PATH, sFile);
        }

        bool bAnyOperationsAborted = false;
        bool bReturn = FileOperation.CopyFiles(this.Handle, sourceFiles, destinationFiles, true, "Copy files", out bAnyOperationsAborted);

        this.lbInstallAgent.Enabled = bReturn && !bAnyOperationsAborted;
    }

    this.picCopyFiles.Image = this.lbInstallAgent.Enabled ? this.statusImageList.Images[0] : this.statusImageList.Images[1];
    this.Refresh();

    // ###########################################
    // ### Install DKIM Signer Excange Agent   ###
    // ###########################################

    if (this.lbInstallAgent.Enabled)
    {
        try
        {
            // First make sure the following Registry key exists HKLM:\SYSTEM\CurrentControlSet\Services\EventLog\Application\Exchange DKIM
            if (EventLog.SourceExists(Constants.DKIM_SIGNER_EVENTLOG_SOURCE))
            {
                // Make sure we recreate the event log source to fix messageResourceFile from versions previous to 2.0.0
                RegistryKey key = Registry.LocalMachine.OpenSubKey(Constants.DKIM_SIGNER_EVENTLOG_REGISTRY, false);
                if (key == null || key.GetValue("EventMessageFile") == null)
                {
                    // Delete the event source for the custom event log 
                    EventLog.DeleteEventSource(Constants.DKIM_SIGNER_EVENTLOG_SOURCE);

                    // Create a new event source for the custom event log 
                    EventSourceCreationData mySourceData = new EventSourceCreationData(Constants.DKIM_SIGNER_EVENTLOG_SOURCE, "Application");
                    mySourceData.MessageResourceFile = @"C:\Windows\Microsoft.NET\Framework\v4.0.30319\EventLogMessages.dll";
                    EventLog.CreateEventSource(mySourceData);
                }
            }
            else
            {
                // Create a new event source for the custom event log 
                EventSourceCreationData mySourceData = new EventSourceCreationData(Constants.DKIM_SIGNER_EVENTLOG_SOURCE, "Application");
                mySourceData.MessageResourceFile = @"C:\Windows\Microsoft.NET\Framework\v4.0.30319\EventLogMessages.dll";
                EventLog.CreateEventSource(mySourceData);
            }

            // Install DKIM Transport Agent in Microsoft Exchange 
            ExchangeServer.InstallDkimTransportAgent();

            this.lbStartService.Enabled = true;
        }
        catch (ExchangeServerException ex)
        {
            MessageBox.Show(this, "Could not install DKIM Agent:\n" + ex.Message, "Error installing agent", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    this.picInstallAgent.Image = this.lbStartService.Enabled ? this.statusImageList.Images[0] : this.statusImageList.Images[1];
    this.Refresh();
    
    // ###########################################
    // ### Start Microsoft Transport service   ###
    // ###########################################

    if (this.lbStartService.Enabled)
    {
        this.transportServiceSuccessStatus = "Running";
        this.transportService.Do(TransportServiceAction.Start);
        this.picStartService.Image = this.transportServiceActionCompleted.WaitOne() ? this.statusImageList.Images[0] : this.statusImageList.Images[1];
    }
    else
    {
        this.picStartService.Image = this.statusImageList.Images[1];
    }

    this.Refresh();

    this.btClose.Enabled = true;
}
```

**Comment by gogglespisano** [comment] 2015-10-28 15:01
Even if you put those values in an XML file, at some point you have to launch another process/installer AND close the current configuration executable or you wont be able to upgrade it during the install without an unnecessary reboot.

**Comment by Pro** [comment] 2015-10-28 16:20
Yes, that's why I don't see any advantage using XML instead of Constants.cs

But Alex is also right, that an installer wouldn't be that simple since it needs to call some Powershell Snippets.

So as a conclusion:
We need to improve our install process and find out why the Configuration.exe isn't properly closed here: https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/MainWindow.cs#L582
I think that one of the threads running in the background isn't stopped properly.

**Comment by AlexLaroche** [comment] 2015-10-28 22:05
Configuration.exe is properly closed. The problem isn't there.

The executable currently reload itself, not the new Configuration executable that will be downloaded later in the install process.

We can use Shadow Copy (http://blogs.msdn.com/b/junfeng/archive/2004/02/09/69919.aspx) feature to load the executable in memory and overwrite the existing executable be cause the file will not be lock (Shadow Copy).

After the new files is copied, we can load the new executable to complete the install process with a specific switch like "-install-continue".

**Comment by Pro** [comment] 2015-10-28 23:57
Ok, then we shouldn't wonder why updating fails!
My first version launched the newly downloaded .exe, which is the right way to do it. (See https://github.com/Pro/dkim-exchange/commit/a2e69eaa15bd64a024fb60094f2a4a2086604500#diff-80fbe899548913d9af44190d7c253f97R756).
But it seems that this was changed during some refactoring, which is bad.
Using the just downloaded .exe allows us to fix bugs in the install process if the old exe fails and of course doesn't lock the currently installed files.

I will change this back as it was.

**Comment by AlexLaroche** [comment] 2015-10-29 00:23
Download the package "Configuration.DkimSigner.zip" from the lastest release, extract the content and execute the "Configuration.DkimSigner.exe" from MainWindow.cs.

You could take example on what have been done in InstallWindow.cs.

The problem could be solve without rollback all the code changes. If you rollback all the changes, you will reintroduce thread bugs that is bad too. A lot of work have been done to make them work without bugs.

**Comment by Pro** [comment] 2015-10-29 07:13
Sorry, my comment wasn't really clear.
I did not mean to rollback the code but to change this behavior back to the old one using the current code

**Closed** 2015-10-30 22:13 UTC
Labels: bug, gui

**Comment by gogglespisano** [comment] 2015-10-31 22:10
I installed 2.1.8 and I was then able to reinstall without getting the file in use error.
