### ISSUE TITLE
Ex2007sp3rp17 edgetransport crash on config reload

### ISSUE THREAD

**Issue by AlxVD** [Pro/dkim-exchange#103] opened 2015-10-29 23:25 UTC
1. Installed v.2.1.7 (for Ex2007sp3rp17 on WinSrv2008R2, .net4.0)
2. Opened settings.xml in notepad++.
3. When I pressed "save" in notepad++ edgetransport.exe crashed with the following error:
```
The transport process failed during message processing with the following call stack: System.IO.IOException: The process cannot access the file 'C:\Program Files\Exchange DkimSigner\settings.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ConfigurationSettings.Settings.Load(String filename) in d:\Programmieren\dkim-exchange\Src\Exchange.DkimSigner\Configuration\Settings.cs:line 65
   at Exchange.DkimSigner.DkimSigningRoutingAgent.LoadSettings() in d:\Programmieren\dkim-exchange\Src\Exchange.DkimSigner\DkimSigningRoutingAgent.cs:line 56
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```
-------------------------------------------------
Previous message in the Application log was: "Detected settings file change. Reloading..."
And the next message was from "error reporting service":
```
Watson report about to be sent to dw20.exe for process id: 13124, with parameters: E12, c-RTL-AMD64, 08.03.0406.000, edgetransport, mscorlib, S.I.__Error.WinIOError, S.IO.IOException, d1de, 02.00.50727.5485.  ErrorReportingEnabled: True
```

**Comment by AlxVD** [comment] 2015-10-30 00:07
Oh... The same crash happend with standard notepad...

**Comment by gogglespisano** [comment] 2015-10-30 00:40
This would be expected.  It can't read the file if you're modifying it.

Why are you making changes to the config file directly, rather than using the configuration program?

**Comment by Pro** [comment] 2015-10-30 07:30
Can you try to first shut down MSExchangeTransport, then modify the file and then start MSExchangeTransport again.
Modifying the file while MSExchangeTransport is running should work and it was already tested on Windows Server 2008 R2 with Exchange 2010...

**Comment by AlxVD** [comment] 2015-10-30 07:56
Of cause it works but... this is a workaround, isn't it?

**Comment by gogglespisano** [comment] 2015-10-30 09:13
The settings code opens the file with fileshare.read.  Saving the file in notepad does not allow another process to open the file with fileshare.read.  It's a race condition.  sometimes it will work, sometimes not.  If you want it to work reliably, you'll need to catch the file sharing exception, wait a bit, and keep trying until notepad has let go of the file.

I've found that the signer loads on each email, loading the settings for each email, at least on ex2010.  that increases the odds of a collision as well as a performance hit.  I started to look into why it doesn't stay loaded in the transport a couple months ago, but didn't have enough time.

what's the need to edit the file manually?  I've never needed to do that.

**Comment by AlxVD** [comment] 2015-10-30 09:37
Reason: Exchange 2007. It's not supported to install .Net 4.5 on a server with Ex2007. And Configuration.DkimSigner.exe depends on 4.5.1.

**Comment by gogglespisano** [comment] 2015-10-30 09:47
OK.

Unless the code is changed to catch the file sharing exception and do a retry of loading the settings, you'll hit this exception at least some of the time, so the work-around is needed right now.

**Comment by Pro** [comment] 2015-10-30 09:49
Modifying the file manually is needed e.g. for the manual installation.
@gogglespisano do you have time to look into this again, why the settings are loaded for each email?

**Comment by gogglespisano** [comment] 2015-10-30 09:55
i'll try to look at it again.  I found it when looking at the edge transport memory leak/growth problem a couple months ago.  I saw that all the domains were loaded on each email (a performance hit) and then found the signer class itself was created on each email.

I started looking at the agent docs but didn't see an answer and then ran out of time.

**Comment by gogglespisano** [comment] 2015-10-30 10:00
The clue was that I get this settings loaded event message for every email message.

        private void LoadSettings()
        {
            Settings config = new Settings();
            config.InitHeadersToSign();

            if(config.Load(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "settings.xml")))
            {
                this.dkimSigner.UpdateSettings(config);
                Logger.logLevel = config.Loglevel;
                Logger.LogInformation("Exchange DKIM settings loaded: " + config.SigningAlgorithm.ToString() + ", Canonicalization Header Algorithm: " + config.HeaderCanonicalization.ToString() + ", Canonicalization Body Algorithm: " + config.BodyCanonicalization.ToString() + ", Number of domains: " + this.dkimSigner.GetDomains().Count);
            }
            else
            {
                Logger.LogError("Couldn't load the settings file.\n");
            }
        }

**Comment by AlxVD** [comment] 2015-10-30 10:23
And yes BTW, config file reloading on each message looks really strange (saw that in the logs).

**Comment by AlxVD** [comment] 2015-10-30 10:26
So don't make new Settings object each time. Create one at agent start and reuse it.

**Comment by gogglespisano** [comment] 2015-10-30 14:23
The settings are only loaded during the creation of the agent.  The transport is creating a new instance of the agent for each message.

What I'm trying to determine is if it is normal for the agent to be created for each message and things like the settings need to be moved to another global object.  I haven't found any exchange documentation that says one way or the other.

**Comment by gogglespisano** [comment] 2015-10-30 14:44
@Pro If you look at the grey listing sdk sample, the settings and databse are loaded in the constructor of the agent factory, and released in the factory Close() method.  The settings are then passed to the agent during the factory CreateAgent() call.

So, the factory is long lived, but the agent is short lived, apparently per message.  I'll try moving the settings code to the factory and see what happens.

**Comment by gogglespisano** [comment] 2015-10-30 15:19
@Pro I moved the code to the factory and it works fine as far as I can tell, including making config changes in the UI.  I would do a pull request, but my editor has different code style (spacing) than the dkim code so my change won't be formatted the same as the current code.  As an aside, that's why I don't do more work on the dkim signer.  The spacing and variable names are too different from the guidelines that I spend more time formatting than working on code.

This is the basic change I made

        public DkimSigningRoutingAgent(DkimSigner dkimSigner)
        {
            this.dkimSigner = dkimSigner;

            this.OnCategorizedMessage += this.WhenMessageCategorized;
        }

and

        public DkimSigningRoutingAgentFactory()
        {
            Logger.LogDebug( "Initializing DkimSigner Service" );

            Settings config = new Settings();
            config.InitHeadersToSign();

            this.dkimSigner = new DkimSigner();

            this.LoadSettings();
            this.WatchSettings();
        }

**Comment by gogglespisano** [comment] 2015-10-30 15:28
In addition to only loading the settings at start and when changed, this also only creates a single file watcher for the settings instead of a new watcher on each message.

I'm watching the edgetransport.exe memory usage to see if that's improved.

**Comment by gogglespisano** [comment] 2015-10-30 18:00
I've also added lock() when loading and using the settings in the signer.

**Closed** 2015-10-30 19:27 UTC

**Comment by Pro** [comment] 2015-10-30 19:28
I included your changes in the commit https://github.com/Pro/dkim-exchange/commit/7edfc90ecf715f6316b96495b7ef9a8856010099
What exactly did you mean by "added lock() ..."

**Comment by gogglespisano** [comment] 2015-10-30 19:48
Look for the 4 lock(this) in this DkimSigner.cs code.  I added it to protect the signing from a concurrent config change.

        public void UpdateSettings(Settings config)
        {
            lock( this )
            {
                // Load the list of domains
                this.domains.Clear();
                foreach( DomainElement domainElement in config.Domains )
                {
                    try
                    {
                        if( domainElement.InitElement( Path.GetDirectoryName( Assembly.GetExecutingAssembly().Location ) ) )
                        {
                            this.domains.Add( domainElement.Domain, domainElement );
                        }
                    }
                    catch( Exception e )
                    {
                        Logger.LogError( e.Message );
                    }
                }

                switch( config.SigningAlgorithm )
                {
                    case DkimAlgorithmKind.RsaSha1:
                        this.hashAlgorithm = new SHA1CryptoServiceProvider();
                        this.hashAlgorithmCryptoCode = "SHA1";
                        this.hashAlgorithmDkimCode = "rsa-sha1";
                        break;
                    case DkimAlgorithmKind.RsaSha256:
                        this.hashAlgorithm = new SHA256CryptoServiceProvider();
                        this.hashAlgorithmCryptoCode = "SHA256";
                        this.hashAlgorithmDkimCode = "rsa-sha256";
                        break;
                    default:
                        throw new ArgumentOutOfRangeException( "signatureKind" );
                }

                this.headerCanonicalization = config.HeaderCanonicalization;
                this.bodyCanonicalization = config.BodyCanonicalization;

                this.eligibleHeaders = new HashSet<string>();
                foreach( string headerToSign in config.HeadersToSign )
                {
                    this.eligibleHeaders.Add( headerToSign.Trim() );
                }

                // The From header must always be signed according to the 
                // DKIM specification.
                if( !this.eligibleHeaders.Contains( "From" ) )
                {
                    this.eligibleHeaders.Add( "From" );
                }
            }
        }

        public Dictionary<string, DomainElement> GetDomains()
        {
            lock( this )
            {
                return this.domains;
            }
        }

        /// <summary>
        /// Returns a value indicating whether or not the unsigned MIME message in the
        /// given stream can be signed. In this case, we iterate until we see the From:
        /// header, and then we only sign it if our domain matches the domain of the From:
        /// address.
        /// </summary>
        /// <param name="inputStream">The input stream.</param>
        /// <returns>The output stream.</returns>
        public string CanSign(DomainElement domain, Stream inputStream)
        {
                if( this.disposed )
                {
                    throw new ObjectDisposedException( "Exchange DkimSigner disposed." );
                }

                inputStream.Seek( 0, SeekOrigin.Begin );

                // Generate the hash for the body
                Logger.LogDebug( "Creating body hash" );
                string bodyHash = this.GetBodyHash( inputStream );
                Logger.LogDebug( "Got body hash: " + bodyHash );
                string unsignedDkimHeader;
                lock( this )
                {
                    unsignedDkimHeader = this.GetUnsignedDkimHeader( domain, bodyHash );
                }

                // Generate the hash for the header
                Logger.LogDebug( "Creating signing header" );
                string signedDkimHeader;
                lock( this )
                {
                    IEnumerable<string> canonicalizedHeaders = this.GetCanonicalizedHeaders( inputStream );
                    signedDkimHeader = this.GetSignedDkimHeader( domain, unsignedDkimHeader, canonicalizedHeaders );
                }
                Logger.LogDebug( "Got signing header: " + signedDkimHeader );

                return signedDkimHeader;
        }

**Comment by gogglespisano** [comment] 2015-10-30 19:50
I didn't spend a lot of time analyzing the best way to add the locks, but I wanted to get some protection.  I think this covers the use of most (maybe all) of the variables modified when the config changes.

**Comment by AlxVD** [comment] 2015-10-30 22:54
Why did you close this issue after fixing absolutely different problem (setting reload on every message)?

**Comment by Pro** [comment] 2015-10-31 08:07
@AlxVD I closed it because this crash was caused by the settings reload. After testing the new version on my server there weren't any crashes or problems. If the problem still persist on your PC, it's always possible to reopen the issue!
