### ISSUE TITLE
Exchange 2019 CU 7

### ISSUE THREAD

**Issue by TS-Steff** [Pro/dkim-exchange#320] opened 2020-11-09 09:42 UTC
### Versions

- **Windows Server Version**: Windows 2019 Standard
- **Exchange Version**: Exchange 2019 CU 7
- **Installed DKIM Exchange Version**: Current

### Description

On installing DKIM says, Your Exchange Version is not supported

**Comment by DJBenson** [comment] 2020-11-11 16:06
Probable duplicate of #317.

I will try and push a fix this evening (GMT).

**Comment by DJBenson** [comment] 2020-11-11 17:14
v3.2.8 pushed - hopefully it resolves this issue.

Please be sure to check the pre-release checkbox.

**Comment by DJBenson** [comment] 2020-11-17 19:33
Assumed fixed - please raise any new defects against the 3.2.8 release.

**Closed by DJBenson** 2020-11-17 19:33 UTC
Labels: bug, duplicate
