### ISSUE TITLE
Now I Have An Install Issue

### ISSUE THREAD

**Issue by RichieRogers** [Pro/dkim-exchange#222] opened 2018-04-04 08:32 UTC
### Versions

- **Windows Server Version**: Windows Server 2016
- **Exchange Version**: Exchange 2016 CU 6
- **Installed DKIM Exchange Version**: None - Trying to install latest

### Description

Unable to install - DKIM Signer reports NOT Installed and install button shows Upgrade (and greyed out)

### Steps to Reproduce

1. Install or manual install

**Expected behavior:** Install button visible and enabled

**Actual behavior:** Install button shows "Upgrade" and is greyed out

Changlog panel reports:
Couldn't get current version
Check your Internet connection or restart the application
![manual install screenshot](https://user-images.githubusercontent.com/6641127/38296994-002b8e48-37eb-11e8-955e-029e650f8be3.png)

**Comment by EddyGurge** [comment] 2018-04-04 21:03
I can confirm as I have the same issue. First time trying to use this.

**Comment by rbfajardo** [comment] 2018-04-04 23:49
See this issue for a compiled version that works:
https://github.com/Pro/dkim-exchange/issues/213

**Comment by Pro** [comment] 2018-05-31 11:09
Duplicate of #198

**Closed by Pro** 2018-05-31 11:09 UTC
