### ISSUE TITLE
v3.0.1 - Event 1057, MSExchange Extensibility

### ISSUE THREAD

**Issue by lukehamburg** [Pro/dkim-exchange#136] opened 2016-01-19 17:19 UTC
We installed 3.0.1 last night on our Exchange 2013 (CU11) server. All was very smooth - thank you so much for this amazing piece of software!

Everything seems to be working well, but I'm seeing lots of Event 1057, MSExchange Extensibility in our Event Logs with the following description:

*Agent 'Exchange DkimSigner' went async but did not call Resume on the new thread, while handling event 'OnCategorizedMessage'*

Is this a known problem, and is there anything I can do to fix it? Or should I just ignore?

**Comment by Pro** [comment] 2016-01-19 17:26
I really thought that this was already fixed in #112 
Looks like the problem is still there.

You can ignore this warning since it doesn't reduce functionality of the signer, but we should try to find a fix for it.
Will close this issue and reopen the other one.

**Closed by Pro** 2016-01-19 17:26 UTC

**Comment by gogglespisano** [comment] 2016-01-19 17:35
@lukehamburg What is the ratio of the event messages to emails processed?  is it 1:1 or something much different?

**Comment by Pro** [comment] 2016-01-19 17:43
Please use issue #112 to discuss the bug so we have it all together. Thanks :)
