### ISSUE TITLE
Can't check available version of dkim-exchange

### ISSUE THREAD

**Issue by unik-web** [Pro/dkim-exchange#224] opened 2018-05-01 07:52 UTC
### Versions

- **Windows Server Version**: Windows Server 2012 R2
- **Exchange Version**: Exchange server 2013
- **Installed DKIM Exchange Version**: 3.0.12

### Description

Can't check available version of dkim-signer. Get this error message "Couldn't get current version.
Check your Internet connection or restart the application."

**Comment by ModernAesthetics** [comment] 2018-05-23 17:28
I get this as well

**Comment by unik-web** [comment] 2018-05-24 06:54
rbfajardo thanks for help. I fixed this issue

**Comment by viorelovidiu** [comment] 2018-05-30 05:42
Hello, recompiled download link not working anymore. Can be uploaded again?
Thanks!

**Comment by Pro** [comment] 2018-05-31 10:17
Duplicate of #198. Will be fixed in newest version released soon

**Closed by Pro** 2018-05-31 10:17 UTC

**Comment by havanazzz** [comment] 2018-10-01 17:58
Hello, Im pretty sure i have Exchnage 2013 U20 installed but Getting Error

Your Microsoft Exchange version isn't supported by the DKIM agent: 15.0.1395.4

Can someone help?

**Comment by jamilnoc** [comment] 2024-01-23 12:47
> Use the fixed version here: #198

can you send me fixed version please? because link down
