### ISSUE TITLE
Changelog and available version not showing

### ISSUE THREAD

**Issue by DanielV88** [Pro/dkim-exchange#213] opened 2018-03-09 13:46 UTC
### Versions

- **Windows Server Version**: 2008 R2
- **Exchange Version**: Exchange 2010 SP3 RU19 - 14.3.123.4
- **Installed DKIM Exchange Version**: 3.0.12

### Description

Error in changelog:
Couldn't get current version
Check your Internet connection or restart application.

Upgrade button is greyed out.
Installed: 3.0.12
Available: Unknown

So the changelog isn't displayed in the Exchange DKIM Signer.

### Troubleshooting steps taken

1. Rebooted server
2. Restarted Exchange DKIM Signer
3. Checked Internet connection

**Expected behavior:**

Correct changelog with latest changes
Available version showing

**Actual behavior:** 
No changelog
No available version

![dkimsigner](https://user-images.githubusercontent.com/6716416/37210302-824c736c-23a8-11e8-9d8d-269f36e31c8f.png)

**Comment by PetieM** [comment] 2018-03-13 05:54
Just want to quickly confirm the tI'm seeing this as well.

**Windows Server Version:** 2008 R2
**Exchange Version:** Exchange 2010 - 14.3.123.4
**Installed DKIM Exchange Version:** 3.0.13

**Comment by o-eazy** [comment] 2018-03-13 14:01
Verifying the problem on my end as well.

Windows Server Version: 2008 R2
Exchange Version: Exchange 2010 SP3 UR17 - 14.3.352.0  (14.3.123.4 shown)
Installed DKIM Exchange Version: 3.0.13 (manually)

The server is also a proxy server. 
It might seem that the UI could not get or use the correct system proxy settings or that some specific (non port80) ports are needed.

**Comment by BVGorp** [comment] 2018-03-14 09:42
Same here

Windows 2016
exchange 2016 CU8
DKIM Exchange Version: 3.0.13

Fiddler web debugger throws error:
HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 10:34:52.620
Connection: close

fiddler.network.https> HTTPS handshake to api.github.com (for #22) failed. System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. < The function requested is not supported

Win32 (SChannel) Native Error Code: 0x80090302

**Comment by olie93** [comment] 2018-03-14 13:11
Same issue for me to
Windows Server Version: 2016
Exchange Version: Exchange 2016 CU8 - 15.1.1415.2
Installed DKIM Exchange Version: 3.0.13 (manually)

**Comment by tsor10** [comment] 2018-03-16 14:25
Same here aswell:
Windows Server 2012R2
Exchange Version: 2013 cu 9
How to manually upgrade?

**Comment by it-world** [comment] 2018-03-18 21:19
same here: 

Windows SBS 2011
Exchange Version: 2010 sp3 ru 19  ( 14.3.123.4)
DKIM: 3.0.13

Windows Server 2016
Exchange Version: 2016 CU8  (15.1.1415.2)
DKIM: 3.0.13

**Comment by Pro** [comment] 2018-05-31 11:01
Duplicate of #198. Will be fixed in newest release

**Closed by Pro** 2018-05-31 11:01 UTC
